# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: volcengine/vod/business/vod_project.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)volcengine/vod/business/vod_project.proto\x12\x1eVolcengine.Vod.Models.Business\"\\\n\x15VodListProjectsResult\x12\x43\n\x0bProjectList\x18\x01 \x03(\x0b\x32..Volcengine.Vod.Models.Business.VodProjectInfo\":\n\x0eVodProjectInfo\x12\x13\n\x0bProjectName\x18\x01 \x01(\t\x12\x13\n\x0b\x44isplayName\x18\x02 \x01(\tB\xce\x01\n)com.volcengine.service.vod.model.businessB\nVodProjectP\x01ZAgithub.com/volcengine/volc-sdk-golang/service/vod/models/business\xa0\x01\x01\xd8\x01\x01\xc2\x02\x00\xca\x02 Volc\\Service\\Vod\\Models\\Business\xe2\x02#Volc\\Service\\Vod\\Models\\GPBMetadatab\x06proto3')



_VODLISTPROJECTSRESULT = DESCRIPTOR.message_types_by_name['VodListProjectsResult']
_VODPROJECTINFO = DESCRIPTOR.message_types_by_name['VodProjectInfo']
VodListProjectsResult = _reflection.GeneratedProtocolMessageType('VodListProjectsResult', (_message.Message,), {
  'DESCRIPTOR' : _VODLISTPROJECTSRESULT,
  '__module__' : 'volcengine.vod.business.vod_project_pb2'
  # @@protoc_insertion_point(class_scope:Volcengine.Vod.Models.Business.VodListProjectsResult)
  })
_sym_db.RegisterMessage(VodListProjectsResult)

VodProjectInfo = _reflection.GeneratedProtocolMessageType('VodProjectInfo', (_message.Message,), {
  'DESCRIPTOR' : _VODPROJECTINFO,
  '__module__' : 'volcengine.vod.business.vod_project_pb2'
  # @@protoc_insertion_point(class_scope:Volcengine.Vod.Models.Business.VodProjectInfo)
  })
_sym_db.RegisterMessage(VodProjectInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)com.volcengine.service.vod.model.businessB\nVodProjectP\001ZAgithub.com/volcengine/volc-sdk-golang/service/vod/models/business\240\001\001\330\001\001\302\002\000\312\002 Volc\\Service\\Vod\\Models\\Business\342\002#Volc\\Service\\Vod\\Models\\GPBMetadata'
  _VODLISTPROJECTSRESULT._serialized_start=77
  _VODLISTPROJECTSRESULT._serialized_end=169
  _VODPROJECTINFO._serialized_start=171
  _VODPROJECTINFO._serialized_end=229
# @@protoc_insertion_point(module_scope)
