# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vod/business/vod_media.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from volcengine.models.vod.business import vod_common_pb2 as vod_dot_business_dot_vod__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='vod/business/vod_media.proto',
  package='Volcengine.Models.Vod.Business',
  syntax='proto3',
  serialized_options=b'\n#com.bytedanceapi.model.vod.businessB\010VodMediaP\001Z9github.com/volcengine/volc-sdk-golang/models/vod/business\240\001\001\330\001\001\302\002\000\312\002\036Volcengine\\Models\\Vod\\Business\342\002\035Volcengine\\Models\\GPBMetadata',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cvod/business/vod_media.proto\x12\x1eVolcengine.Models.Vod.Business\x1a\x1dvod/business/vod_common.proto\"\xb8\x01\n\x11VodMediaBasicInfo\x12\x11\n\tSpaceName\x18\x01 \x01(\t\x12\x0b\n\x03Vid\x18\x02 \x01(\t\x12\r\n\x05Title\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x04 \x01(\t\x12\x11\n\tPosterUri\x18\x05 \x01(\t\x12\x15\n\rPublishStatus\x18\x06 \x01(\t\x12\x13\n\x0b\x41uditStatus\x18\x07 \x01(\x03\x12\x0c\n\x04Tags\x18\x08 \x03(\t\x12\x12\n\nCreateTime\x18\t \x01(\t\"\xe1\x01\n\x0cVodVideoInfo\x12\x44\n\tBasicInfo\x18\x01 \x01(\x0b\x32\x31.Volcengine.Models.Vod.Business.VodMediaBasicInfo\x12\x41\n\nSourceInfo\x18\x02 \x01(\x0b\x32-.Volcengine.Models.Vod.Business.VodSourceInfo\x12H\n\x0eTranscodeInfos\x18\x03 \x03(\x0b\x32\x30.Volcengine.Models.Vod.Business.VodTranscodeInfo\"q\n\x14VodGetVideoInfosData\x12\x43\n\rVideoInfoList\x18\x01 \x03(\x0b\x32,.Volcengine.Models.Vod.Business.VodVideoInfo\x12\x14\n\x0cNotExistVids\x18\x02 \x03(\t\"2\n\x10VodStoreUriGroup\x12\x0b\n\x03Vid\x18\x01 \x01(\t\x12\x11\n\tStoreUris\x18\x02 \x03(\t\"u\n\x13VodGetRecPosterData\x12H\n\x0eStoreUriGroups\x18\x01 \x03(\x0b\x32\x30.Volcengine.Models.Vod.Business.VodStoreUriGroup\x12\x14\n\x0cNotExistVids\x18\x02 \x03(\tB\xb6\x01\n#com.bytedanceapi.model.vod.businessB\x08VodMediaP\x01Z9github.com/volcengine/volc-sdk-golang/models/vod/business\xa0\x01\x01\xd8\x01\x01\xc2\x02\x00\xca\x02\x1eVolcengine\\Models\\Vod\\Business\xe2\x02\x1dVolcengine\\Models\\GPBMetadatab\x06proto3'
  ,
  dependencies=[vod_dot_business_dot_vod__common__pb2.DESCRIPTOR,])




_VODMEDIABASICINFO = _descriptor.Descriptor(
  name='VodMediaBasicInfo',
  full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SpaceName', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.SpaceName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Vid', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.Vid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Title', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.Title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Description', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.Description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PosterUri', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.PosterUri', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='PublishStatus', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.PublishStatus', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AuditStatus', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.AuditStatus', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Tags', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.Tags', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CreateTime', full_name='Volcengine.Models.Vod.Business.VodMediaBasicInfo.CreateTime', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=280,
)


_VODVIDEOINFO = _descriptor.Descriptor(
  name='VodVideoInfo',
  full_name='Volcengine.Models.Vod.Business.VodVideoInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='BasicInfo', full_name='Volcengine.Models.Vod.Business.VodVideoInfo.BasicInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SourceInfo', full_name='Volcengine.Models.Vod.Business.VodVideoInfo.SourceInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TranscodeInfos', full_name='Volcengine.Models.Vod.Business.VodVideoInfo.TranscodeInfos', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=508,
)


_VODGETVIDEOINFOSDATA = _descriptor.Descriptor(
  name='VodGetVideoInfosData',
  full_name='Volcengine.Models.Vod.Business.VodGetVideoInfosData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='VideoInfoList', full_name='Volcengine.Models.Vod.Business.VodGetVideoInfosData.VideoInfoList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NotExistVids', full_name='Volcengine.Models.Vod.Business.VodGetVideoInfosData.NotExistVids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=510,
  serialized_end=623,
)


_VODSTOREURIGROUP = _descriptor.Descriptor(
  name='VodStoreUriGroup',
  full_name='Volcengine.Models.Vod.Business.VodStoreUriGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Vid', full_name='Volcengine.Models.Vod.Business.VodStoreUriGroup.Vid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='StoreUris', full_name='Volcengine.Models.Vod.Business.VodStoreUriGroup.StoreUris', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=625,
  serialized_end=675,
)


_VODGETRECPOSTERDATA = _descriptor.Descriptor(
  name='VodGetRecPosterData',
  full_name='Volcengine.Models.Vod.Business.VodGetRecPosterData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='StoreUriGroups', full_name='Volcengine.Models.Vod.Business.VodGetRecPosterData.StoreUriGroups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='NotExistVids', full_name='Volcengine.Models.Vod.Business.VodGetRecPosterData.NotExistVids', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=677,
  serialized_end=794,
)

_VODVIDEOINFO.fields_by_name['BasicInfo'].message_type = _VODMEDIABASICINFO
_VODVIDEOINFO.fields_by_name['SourceInfo'].message_type = vod_dot_business_dot_vod__common__pb2._VODSOURCEINFO
_VODVIDEOINFO.fields_by_name['TranscodeInfos'].message_type = vod_dot_business_dot_vod__common__pb2._VODTRANSCODEINFO
_VODGETVIDEOINFOSDATA.fields_by_name['VideoInfoList'].message_type = _VODVIDEOINFO
_VODGETRECPOSTERDATA.fields_by_name['StoreUriGroups'].message_type = _VODSTOREURIGROUP
DESCRIPTOR.message_types_by_name['VodMediaBasicInfo'] = _VODMEDIABASICINFO
DESCRIPTOR.message_types_by_name['VodVideoInfo'] = _VODVIDEOINFO
DESCRIPTOR.message_types_by_name['VodGetVideoInfosData'] = _VODGETVIDEOINFOSDATA
DESCRIPTOR.message_types_by_name['VodStoreUriGroup'] = _VODSTOREURIGROUP
DESCRIPTOR.message_types_by_name['VodGetRecPosterData'] = _VODGETRECPOSTERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VodMediaBasicInfo = _reflection.GeneratedProtocolMessageType('VodMediaBasicInfo', (_message.Message,), {
  'DESCRIPTOR' : _VODMEDIABASICINFO,
  '__module__' : 'vod.business.vod_media_pb2'
  # @@protoc_insertion_point(class_scope:Volcengine.Models.Vod.Business.VodMediaBasicInfo)
  })
_sym_db.RegisterMessage(VodMediaBasicInfo)

VodVideoInfo = _reflection.GeneratedProtocolMessageType('VodVideoInfo', (_message.Message,), {
  'DESCRIPTOR' : _VODVIDEOINFO,
  '__module__' : 'vod.business.vod_media_pb2'
  # @@protoc_insertion_point(class_scope:Volcengine.Models.Vod.Business.VodVideoInfo)
  })
_sym_db.RegisterMessage(VodVideoInfo)

VodGetVideoInfosData = _reflection.GeneratedProtocolMessageType('VodGetVideoInfosData', (_message.Message,), {
  'DESCRIPTOR' : _VODGETVIDEOINFOSDATA,
  '__module__' : 'vod.business.vod_media_pb2'
  # @@protoc_insertion_point(class_scope:Volcengine.Models.Vod.Business.VodGetVideoInfosData)
  })
_sym_db.RegisterMessage(VodGetVideoInfosData)

VodStoreUriGroup = _reflection.GeneratedProtocolMessageType('VodStoreUriGroup', (_message.Message,), {
  'DESCRIPTOR' : _VODSTOREURIGROUP,
  '__module__' : 'vod.business.vod_media_pb2'
  # @@protoc_insertion_point(class_scope:Volcengine.Models.Vod.Business.VodStoreUriGroup)
  })
_sym_db.RegisterMessage(VodStoreUriGroup)

VodGetRecPosterData = _reflection.GeneratedProtocolMessageType('VodGetRecPosterData', (_message.Message,), {
  'DESCRIPTOR' : _VODGETRECPOSTERDATA,
  '__module__' : 'vod.business.vod_media_pb2'
  # @@protoc_insertion_point(class_scope:Volcengine.Models.Vod.Business.VodGetRecPosterData)
  })
_sym_db.RegisterMessage(VodGetRecPosterData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
